msg_fun_hh = "HH bedeutet für uns seit mehreren Jahren Hatted Hacker - ein Hacker, der seinen ersten Hut verdient hat."
msg_fun_afd = "Away From Device sagt ein Hacktivist, wenn jemand sein Telefon eine Weile unbeaufsichtigt lässt."
